title : Puhao
tagline: Blog Tagline
author :
  name : Puhao Yuan
  email : yuanpuhao@gmail.com
  github : puhao
  twitter : xxoo
  feedburner : ooxx

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
